"""Add profile_photo to users table

Revision ID: 7cf7f84b6948
Revises: be9c27cb5797
Create Date: 2025-11-18 22:13:08.393011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cf7f84b6948'
down_revision = 'be9c27cb5797'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notice')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_photo', sa.String(length=255), nullable=True))
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.drop_column('email_verification_token')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verification_token', sa.VARCHAR(length=100), nullable=True))
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
        batch_op.drop_column('profile_photo')

    op.create_table('notice',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), nullable=False),
    sa.Column('message', sa.TEXT(), nullable=False),
    sa.Column('created_by', sa.INTEGER(), nullable=False),
    sa.Column('target_audience', sa.VARCHAR(length=20), nullable=False),
    sa.Column('branch', sa.VARCHAR(length=10), nullable=True),
    sa.Column('year', sa.INTEGER(), nullable=True),
    sa.Column('is_important', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('expires_at', sa.DATETIME(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
