"""Add slot_type to timetable_slots

Revision ID: d47fc5bcc9e5
Revises: 
Create Date: 2025-11-17 22:31:48.203773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd47fc5bcc9e5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subject')
    op.drop_table('email_log')
    op.drop_table('rgpv_scheme')
    op.drop_table('timetable_slot')
    op.drop_table('student')
    op.drop_table('password_reset_otp')
    op.drop_table('attendance_report')
    op.drop_table('faculty')
    op.drop_table('professor_subject')
    op.drop_table('user')
    with op.batch_alter_table('mid_term_marks', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    with op.batch_alter_table('timetable_slots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slot_type', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timetable_slots', schema=None) as batch_op:
        batch_op.drop_column('slot_type')

    with op.batch_alter_table('mid_term_marks', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=80), nullable=False),
    sa.Column('fullname', sa.VARCHAR(length=150), nullable=False),
    sa.Column('email', sa.VARCHAR(length=150), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=200), nullable=False),
    sa.Column('role', sa.VARCHAR(length=20), nullable=False),
    sa.Column('branch', sa.VARCHAR(length=50), nullable=True),
    sa.Column('student_roll', sa.VARCHAR(length=50), nullable=True),
    sa.Column('email_verified', sa.BOOLEAN(), nullable=True),
    sa.Column('email_verification_token', sa.VARCHAR(length=100), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['student_roll'], ['student.roll'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('professor_subject',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('professor_id', sa.INTEGER(), nullable=False),
    sa.Column('subject_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['professor_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('faculty',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), nullable=False),
    sa.Column('phone', sa.VARCHAR(length=15), nullable=True),
    sa.Column('specialization', sa.VARCHAR(length=100), nullable=True),
    sa.Column('branches', sa.VARCHAR(length=100), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('attendance_report',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('subject_id', sa.INTEGER(), nullable=True),
    sa.Column('professor_id', sa.INTEGER(), nullable=True),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('report_path', sa.VARCHAR(length=300), nullable=False),
    sa.Column('report_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('branch', sa.VARCHAR(length=50), nullable=True),
    sa.Column('year', sa.INTEGER(), nullable=True),
    sa.Column('semester', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['professor_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('password_reset_otp',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('otp_code', sa.VARCHAR(length=10), nullable=False),
    sa.Column('expires_at', sa.DATETIME(), nullable=False),
    sa.Column('used', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('roll', sa.VARCHAR(length=50), nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), nullable=False),
    sa.Column('branch', sa.VARCHAR(length=50), nullable=False),
    sa.Column('year', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('roll')
    )
    op.create_table('timetable_slot',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('branch', sa.VARCHAR(length=10), nullable=False),
    sa.Column('year', sa.INTEGER(), nullable=False),
    sa.Column('semester', sa.INTEGER(), nullable=False),
    sa.Column('day_of_week', sa.INTEGER(), nullable=False),
    sa.Column('period_number', sa.INTEGER(), nullable=False),
    sa.Column('subject_id', sa.INTEGER(), nullable=False),
    sa.Column('faculty_id', sa.INTEGER(), nullable=False),
    sa.Column('room_number', sa.VARCHAR(length=20), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculty.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('branch', 'year', 'semester', 'day_of_week', 'period_number', name=op.f('unique_slot'))
    )
    op.create_table('rgpv_scheme',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('branch', sa.VARCHAR(length=10), nullable=False),
    sa.Column('year', sa.INTEGER(), nullable=False),
    sa.Column('semester', sa.INTEGER(), nullable=False),
    sa.Column('subject_id', sa.INTEGER(), nullable=False),
    sa.Column('lectures_per_week', sa.INTEGER(), nullable=False),
    sa.Column('tutorial_per_week', sa.INTEGER(), nullable=True),
    sa.Column('practical_per_week', sa.INTEGER(), nullable=True),
    sa.Column('credits', sa.INTEGER(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('email_log',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('recipient', sa.VARCHAR(length=150), nullable=False),
    sa.Column('subject', sa.VARCHAR(length=200), nullable=False),
    sa.Column('body', sa.TEXT(), nullable=True),
    sa.Column('sent_at', sa.DATETIME(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subject',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('code', sa.VARCHAR(length=50), nullable=True),
    sa.Column('name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('branch', sa.VARCHAR(length=50), nullable=False),
    sa.Column('semester', sa.INTEGER(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
