"""Add missing columns for smart tests

Revision ID: dbb5ad0b5b44
Revises: fb31915e65d4
Create Date: 2025-11-20 11:44:44.484715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbb5ad0b5b44'
down_revision = 'fb31915e65d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    with op.batch_alter_table('student_answers', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_student_answers_evaluated_by', 'users', ['evaluated_by'],
                                    ['id'])

    with op.batch_alter_table('test_attempts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expected_end_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('tab_switch_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_activity', sa.DateTime(), nullable=True))

    with op.batch_alter_table('tests', schema=None) as batch_op:
        batch_op.alter_column('available_from',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('available_until',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.drop_column('start_time')
        batch_op.drop_column('end_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end_time', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('start_time', sa.DATETIME(), nullable=False))
        batch_op.alter_column('available_until',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('available_from',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('test_attempts', schema=None) as batch_op:
        batch_op.drop_column('last_activity')
        batch_op.drop_column('tab_switch_count')
        batch_op.drop_column('expected_end_time')

    with op.batch_alter_table('student_answers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    # ### end Alembic commands ###
