"""Add status field to Test model

Revision ID: e7520fa10af5
Revises: dbb5ad0b5b44
Create Date: 2025-11-20 15:46:40.515628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7520fa10af5'
down_revision = 'dbb5ad0b5b44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_questions')
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    with op.batch_alter_table('student_answers', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['evaluated_by'], ['id'])

    with op.batch_alter_table('tests', schema=None) as batch_op:
        batch_op.alter_column('available_from',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('available_until',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('start_time',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('end_time',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tests', schema=None) as batch_op:
        batch_op.alter_column('end_time',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('start_time',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('available_until',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('available_from',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('student_answers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    op.create_table('_alembic_tmp_questions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('test_id', sa.INTEGER(), nullable=False),
    sa.Column('section_id', sa.INTEGER(), nullable=True),
    sa.Column('question_type', sa.VARCHAR(length=20), server_default=sa.text("'mcq'"), nullable=False),
    sa.Column('question_text', sa.TEXT(), nullable=False),
    sa.Column('option_a', sa.VARCHAR(length=500), nullable=True),
    sa.Column('option_b', sa.VARCHAR(length=500), nullable=True),
    sa.Column('option_c', sa.VARCHAR(length=500), nullable=True),
    sa.Column('option_d', sa.VARCHAR(length=500), nullable=True),
    sa.Column('correct_answer', sa.VARCHAR(length=1), nullable=True),
    sa.Column('expected_answer', sa.TEXT(), nullable=True),
    sa.Column('word_limit', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('attachment_required', sa.BOOLEAN(), server_default=sa.text('(FALSE)'), nullable=True),
    sa.Column('code_template', sa.TEXT(), nullable=True),
    sa.Column('test_cases', sa.TEXT(), nullable=True),
    sa.Column('programming_language', sa.VARCHAR(length=50), nullable=True),
    sa.Column('marks', sa.FLOAT(), server_default=sa.text('1'), nullable=False),
    sa.Column('question_order', sa.INTEGER(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['question_sections.id'], ),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
