"""Add advanced test management system with sections and multiple question types

Revision ID: fb31915e65d4
Revises: 7cf7f84b6948
Create Date: 2025-11-19 17:54:26.941499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb31915e65d4'
down_revision = '7cf7f84b6948'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('question_type', sa.String(length=20), nullable=False),
    sa.Column('total_marks', sa.Float(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('section_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('section_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('question_type', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('expected_answer', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('word_limit', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('attachment_required', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('code_template', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('test_cases', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('programming_language', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('option_a',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
        batch_op.alter_column('option_b',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
        batch_op.alter_column('option_c',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
        batch_op.alter_column('option_d',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
        batch_op.alter_column('correct_answer',
               existing_type=sa.VARCHAR(length=1),
               nullable=True)
        batch_op.alter_column('marks',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.create_foreign_key(None, 'question_sections', ['section_id'], ['id'])

    with op.batch_alter_table('student_answers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('theory_answer', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('code_answer', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('attached_file', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('evaluated_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('evaluated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('feedback', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['evaluated_by'], ['id'])

    with op.batch_alter_table('test_attempts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('tests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question_types', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('test_type', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tests', schema=None) as batch_op:
        batch_op.drop_column('test_type')
        batch_op.drop_column('question_types')

    with op.batch_alter_table('test_attempts', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('student_answers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('created_at')
        batch_op.drop_column('feedback')
        batch_op.drop_column('evaluated_at')
        batch_op.drop_column('evaluated_by')
        batch_op.drop_column('attached_file')
        batch_op.drop_column('code_answer')
        batch_op.drop_column('theory_answer')

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('marks',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('correct_answer',
               existing_type=sa.VARCHAR(length=1),
               nullable=False)
        batch_op.alter_column('option_d',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
        batch_op.alter_column('option_c',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
        batch_op.alter_column('option_b',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
        batch_op.alter_column('option_a',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
        batch_op.drop_column('created_at')
        batch_op.drop_column('programming_language')
        batch_op.drop_column('test_cases')
        batch_op.drop_column('code_template')
        batch_op.drop_column('attachment_required')
        batch_op.drop_column('word_limit')
        batch_op.drop_column('expected_answer')
        batch_op.drop_column('question_type')
        batch_op.drop_column('section_id')

    op.drop_table('question_sections')
    # ### end Alembic commands ###
