import {
  Student,
  SubjectAttendance,
  AttendanceDayLog,
  TimetableSlot,
  OnlineTest,
  StudyNote,
  Notice,
  ExamMark,
  FeeStatus,
} from '../types';

export const mockStudent: Student = {
  id: 101,
  roll: '0191CS221045',
  name: 'Ravi Kumar',
  branch: 'Computer Science & Engineering',
  year: 3,
  semester: 6,
  email: 'ravi.kumar@sbitm.edu.in',
  phone: '+91 98765 43210',
  profilePhoto: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
  overallAttendance: 81.5,
  totalPresent: 146,
  totalClasses: 179,
  academicYear: '2025-2026',
};

export const mockSubjectAttendance: SubjectAttendance[] = [
  {
    subjectId: 1,
    subjectCode: 'CS-601',
    subjectName: 'Computer Networks',
    professorName: 'Dr. Alok Verma',
    totalLectures: 38,
    attendedLectures: 33,
    percentage: 86.8,
    status: 'safe',
    classesNeededFor75: 0,
    classesCanSkip: 5,
  },
  {
    subjectId: 2,
    subjectCode: 'CS-602',
    subjectName: 'Database Management Systems',
    professorName: 'Prof. Sneha Sharma',
    totalLectures: 42,
    attendedLectures: 35,
    percentage: 83.3,
    status: 'safe',
    classesNeededFor75: 0,
    classesCanSkip: 4,
  },
  {
    subjectId: 3,
    subjectCode: 'CS-603',
    subjectName: 'Machine Learning & AI',
    professorName: 'Dr. Rajesh Pandey',
    totalLectures: 36,
    attendedLectures: 26,
    percentage: 72.2,
    status: 'warning',
    classesNeededFor75: 4,
    classesCanSkip: 0,
  },
  {
    subjectId: 4,
    subjectCode: 'CS-604',
    subjectName: 'Operating Systems & Linux',
    professorName: 'Prof. Amit Patel',
    totalLectures: 34,
    attendedLectures: 29,
    percentage: 85.3,
    status: 'safe',
    classesNeededFor75: 0,
    classesCanSkip: 4,
  },
  {
    subjectId: 5,
    subjectCode: 'CS-605',
    subjectName: 'Cloud Computing & DevOps',
    professorName: 'Prof. Neha Gupta',
    totalLectures: 29,
    attendedLectures: 23,
    percentage: 79.3,
    status: 'safe',
    classesNeededFor75: 0,
    classesCanSkip: 1,
  },
];

export const mockRecentAttendanceLogs: AttendanceDayLog[] = [
  {
    id: 'att-1',
    date: '2026-09-19',
    dayName: 'Friday',
    subjectName: 'Computer Networks',
    subjectCode: 'CS-601',
    period: 1,
    time: '09:30 AM - 10:30 AM',
    status: 'present',
  },
  {
    id: 'att-2',
    date: '2026-09-19',
    dayName: 'Friday',
    subjectName: 'Database Systems Lab',
    subjectCode: 'CS-602L',
    period: 2,
    time: '10:30 AM - 12:30 PM',
    status: 'present',
  },
  {
    id: 'att-3',
    date: '2026-09-18',
    dayName: 'Thursday',
    subjectName: 'Machine Learning & AI',
    subjectCode: 'CS-603',
    period: 3,
    time: '01:15 PM - 02:15 PM',
    status: 'absent',
  },
  {
    id: 'att-4',
    date: '2026-09-18',
    dayName: 'Thursday',
    subjectName: 'Operating Systems',
    subjectCode: 'CS-604',
    period: 4,
    time: '02:15 PM - 03:15 PM',
    status: 'present',
  },
  {
    id: 'att-5',
    date: '2026-09-17',
    dayName: 'Wednesday',
    subjectName: 'Cloud Computing',
    subjectCode: 'CS-605',
    period: 1,
    time: '09:30 AM - 10:30 AM',
    status: 'present',
  },
];

export const mockTimetable: TimetableSlot[] = [
  // Monday (dayOfWeek = 1)
  {
    id: 1,
    dayOfWeek: 1,
    dayName: 'Monday',
    periodNumber: 1,
    timeSlot: '09:30 AM - 10:30 AM',
    subjectCode: 'CS-601',
    subjectName: 'Computer Networks',
    facultyName: 'Dr. Alok Verma',
    roomNumber: 'LH-302',
    slotType: 'lecture',
  },
  {
    id: 2,
    dayOfWeek: 1,
    dayName: 'Monday',
    periodNumber: 2,
    timeSlot: '10:30 AM - 11:30 AM',
    subjectCode: 'CS-602',
    subjectName: 'Database Management Systems',
    facultyName: 'Prof. Sneha Sharma',
    roomNumber: 'LH-302',
    slotType: 'lecture',
  },
  {
    id: 3,
    dayOfWeek: 1,
    dayName: 'Monday',
    periodNumber: 3,
    timeSlot: '11:30 AM - 01:30 PM',
    subjectCode: 'CS-602L',
    subjectName: 'DBMS & SQL Laboratory',
    facultyName: 'Prof. Sneha Sharma',
    roomNumber: 'Lab-4 (CS)',
    slotType: 'lab',
    isCommon: false,
  },
  {
    id: 4,
    dayOfWeek: 1,
    dayName: 'Monday',
    periodNumber: 4,
    timeSlot: '02:15 PM - 03:15 PM',
    subjectCode: 'CS-604',
    subjectName: 'Operating Systems',
    facultyName: 'Prof. Amit Patel',
    roomNumber: 'LH-302',
    slotType: 'lecture',
  },

  // Tuesday (dayOfWeek = 2)
  {
    id: 5,
    dayOfWeek: 2,
    dayName: 'Tuesday',
    periodNumber: 1,
    timeSlot: '09:30 AM - 10:30 AM',
    subjectCode: 'CS-603',
    subjectName: 'Machine Learning & AI',
    facultyName: 'Dr. Rajesh Pandey',
    roomNumber: 'LH-302',
    slotType: 'lecture',
    isCommon: true,
  },
  {
    id: 6,
    dayOfWeek: 2,
    dayName: 'Tuesday',
    periodNumber: 2,
    timeSlot: '10:30 AM - 11:30 AM',
    subjectCode: 'CS-601',
    subjectName: 'Computer Networks',
    facultyName: 'Dr. Alok Verma',
    roomNumber: 'LH-302',
    slotType: 'lecture',
  },
  {
    id: 7,
    dayOfWeek: 2,
    dayName: 'Tuesday',
    periodNumber: 3,
    timeSlot: '11:30 AM - 01:30 PM',
    subjectCode: 'CS-603L',
    subjectName: 'AI & Python Lab',
    facultyName: 'Dr. Rajesh Pandey',
    roomNumber: 'Lab-2 (AI)',
    slotType: 'lab',
  },
  {
    id: 8,
    dayOfWeek: 2,
    dayName: 'Tuesday',
    periodNumber: 4,
    timeSlot: '02:15 PM - 03:15 PM',
    subjectCode: 'CS-605',
    subjectName: 'Cloud Computing & DevOps',
    facultyName: 'Prof. Neha Gupta',
    roomNumber: 'LH-302',
    slotType: 'lecture',
  },

  // Wednesday (dayOfWeek = 3)
  {
    id: 9,
    dayOfWeek: 3,
    dayName: 'Wednesday',
    periodNumber: 1,
    timeSlot: '09:30 AM - 10:30 AM',
    subjectCode: 'CS-602',
    subjectName: 'Database Management Systems',
    facultyName: 'Prof. Sneha Sharma',
    roomNumber: 'LH-302',
    slotType: 'lecture',
  },
  {
    id: 10,
    dayOfWeek: 3,
    dayName: 'Wednesday',
    periodNumber: 2,
    timeSlot: '10:30 AM - 11:30 AM',
    subjectCode: 'CS-604',
    subjectName: 'Operating Systems',
    facultyName: 'Prof. Amit Patel',
    roomNumber: 'LH-302',
    slotType: 'lecture',
  },
  {
    id: 11,
    dayOfWeek: 3,
    dayName: 'Wednesday',
    periodNumber: 3,
    timeSlot: '01:15 PM - 02:15 PM',
    subjectCode: 'CS-603',
    subjectName: 'Machine Learning & AI',
    facultyName: 'Dr. Rajesh Pandey',
    roomNumber: 'LH-302',
    slotType: 'lecture',
  },
  {
    id: 12,
    dayOfWeek: 3,
    dayName: 'Wednesday',
    periodNumber: 4,
    timeSlot: '02:15 PM - 03:15 PM',
    subjectCode: 'CS-605',
    subjectName: 'Cloud Computing & DevOps',
    facultyName: 'Prof. Neha Gupta',
    roomNumber: 'LH-302',
    slotType: 'lecture',
  },

  // Thursday (dayOfWeek = 4)
  {
    id: 13,
    dayOfWeek: 4,
    dayName: 'Thursday',
    periodNumber: 1,
    timeSlot: '09:30 AM - 10:30 AM',
    subjectCode: 'CS-601',
    subjectName: 'Computer Networks',
    facultyName: 'Dr. Alok Verma',
    roomNumber: 'LH-302',
    slotType: 'lecture',
  },
  {
    id: 14,
    dayOfWeek: 4,
    dayName: 'Thursday',
    periodNumber: 2,
    timeSlot: '10:30 AM - 12:30 PM',
    subjectCode: 'CS-601L',
    subjectName: 'Networking & Cisco Packet Tracer Lab',
    facultyName: 'Dr. Alok Verma',
    roomNumber: 'Lab-1 (Networks)',
    slotType: 'lab',
  },
  {
    id: 15,
    dayOfWeek: 4,
    dayName: 'Thursday',
    periodNumber: 3,
    timeSlot: '01:15 PM - 02:15 PM',
    subjectCode: 'CS-604',
    subjectName: 'Operating Systems',
    facultyName: 'Prof. Amit Patel',
    roomNumber: 'LH-302',
    slotType: 'lecture',
  },
  {
    id: 16,
    dayOfWeek: 4,
    dayName: 'Thursday',
    periodNumber: 4,
    timeSlot: '02:15 PM - 03:15 PM',
    subjectCode: 'CS-603',
    subjectName: 'Machine Learning & AI',
    facultyName: 'Dr. Rajesh Pandey',
    roomNumber: 'LH-302',
    slotType: 'lecture',
  },

  // Friday (dayOfWeek = 5)
  {
    id: 17,
    dayOfWeek: 5,
    dayName: 'Friday',
    periodNumber: 1,
    timeSlot: '09:30 AM - 10:30 AM',
    subjectCode: 'CS-605',
    subjectName: 'Cloud Computing & AWS',
    facultyName: 'Prof. Neha Gupta',
    roomNumber: 'LH-302',
    slotType: 'lecture',
  },
  {
    id: 18,
    dayOfWeek: 5,
    dayName: 'Friday',
    periodNumber: 2,
    timeSlot: '10:30 AM - 11:30 AM',
    subjectCode: 'CS-602',
    subjectName: 'Database Management Systems',
    facultyName: 'Prof. Sneha Sharma',
    roomNumber: 'LH-302',
    slotType: 'lecture',
  },
  {
    id: 19,
    dayOfWeek: 5,
    dayName: 'Friday',
    periodNumber: 3,
    timeSlot: '11:30 AM - 01:30 PM',
    subjectCode: 'CS-605L',
    subjectName: 'Cloud & DevOps Lab',
    facultyName: 'Prof. Neha Gupta',
    roomNumber: 'Lab-3 (Cloud)',
    slotType: 'lab',
  },

  // Saturday (dayOfWeek = 6)
  {
    id: 20,
    dayOfWeek: 6,
    dayName: 'Saturday',
    periodNumber: 1,
    timeSlot: '10:00 AM - 12:00 PM',
    subjectCode: 'CS-606',
    subjectName: 'Major Project Mentoring & Seminar',
    facultyName: 'HOD CSE Dept.',
    roomNumber: 'Seminar Hall-1',
    slotType: 'lecture',
  },
];

export const mockTests: OnlineTest[] = [
  {
    id: 101,
    title: 'Mid-Sem Practice Test: Computer Networks & TCP/IP',
    subjectName: 'Computer Networks',
    subjectCode: 'CS-601',
    durationMinutes: 20,
    totalQuestions: 5,
    totalMarks: 25,
    deadline: 'Tomorrow, 11:59 PM',
    status: 'available',
    questions: [
      {
        id: 1,
        questionText: 'Which OSI layer is responsible for end-to-end reliable communication?',
        options: ['Physical Layer', 'Data Link Layer', 'Transport Layer', 'Session Layer'],
        correctOptionIndex: 2,
        explanation: 'Transport layer provides host-to-host communication and error recovery (TCP/UDP).',
      },
      {
        id: 2,
        questionText: 'What is the standard port number for HTTPS secure web traffic?',
        options: ['80', '443', '8080', '22'],
        correctOptionIndex: 1,
        explanation: 'HTTPS default port is 443; HTTP uses port 80.',
      },
      {
        id: 3,
        questionText: 'Which protocol is used to dynamically assign IP addresses to hosts on a network?',
        options: ['DHCP', 'DNS', 'ARP', 'ICMP'],
        correctOptionIndex: 0,
        explanation: 'DHCP (Dynamic Host Configuration Protocol) assigns dynamic IP addresses automatically.',
      },
      {
        id: 4,
        questionText: 'In CIDR notation /24, how many usable host IP addresses are available?',
        options: ['256', '254', '128', '512'],
        correctOptionIndex: 1,
        explanation: 'A /24 subnet has 2^8 = 256 total IPs, minus network & broadcast = 254 usable.',
      },
      {
        id: 5,
        questionText: 'Which routing protocol is an exterior gateway protocol commonly used on the Internet?',
        options: ['OSPF', 'RIP', 'BGP', 'EIGRP'],
        correctOptionIndex: 2,
        explanation: 'BGP (Border Gateway Protocol) routes packets between different Autonomous Systems across the internet.',
      },
    ],
  },
  {
    id: 102,
    title: 'Quiz 2: SQL Joins, Indexing & ACID Properties',
    subjectName: 'Database Management Systems',
    subjectCode: 'CS-602',
    durationMinutes: 15,
    totalQuestions: 4,
    totalMarks: 20,
    deadline: '24 Sep 2026',
    status: 'available',
    questions: [
      {
        id: 1,
        questionText: 'Which normal form eliminates partial functional dependency?',
        options: ['1NF', '2NF', '3NF', 'BCNF'],
        correctOptionIndex: 1,
        explanation: '2NF removes partial functional dependencies on candidate keys.',
      },
      {
        id: 2,
        questionText: 'What does the "I" in ACID database properties stand for?',
        options: ['Integrity', 'Isolation', 'Indexing', 'Iteration'],
        correctOptionIndex: 1,
        explanation: 'Isolation ensures concurrent transactions execute independently.',
      },
      {
        id: 3,
        questionText: 'Which index structure is primarily used by modern relational databases for fast range queries?',
        options: ['B+ Tree', 'Hash Map', 'Red-Black Tree', 'Linked List'],
        correctOptionIndex: 0,
        explanation: 'B+ Tree keeps keys in sorted order with linked leaf nodes for range scans.',
      },
      {
        id: 4,
        questionText: 'What type of JOIN returns all records when there is a match in either left or right table?',
        options: ['INNER JOIN', 'LEFT JOIN', 'FULL OUTER JOIN', 'CROSS JOIN'],
        correctOptionIndex: 2,
        explanation: 'FULL OUTER JOIN returns matching records and non-matching records filled with NULLs.',
      },
    ],
  },
  {
    id: 103,
    title: 'Surprise Quiz: Supervised vs Unsupervised ML',
    subjectName: 'Machine Learning & AI',
    subjectCode: 'CS-603',
    durationMinutes: 15,
    totalQuestions: 4,
    totalMarks: 20,
    deadline: 'Completed on 14 Sep',
    status: 'completed',
    scoredMarks: 18,
  },
];

export const mockNotes: StudyNote[] = [
  {
    id: 1,
    title: 'Unit 3: Routing Algorithms (Dijkstra & Bellman-Ford)',
    subjectName: 'Computer Networks',
    subjectCode: 'CS-601',
    professorName: 'Dr. Alok Verma',
    description: 'Comprehensive handwritten slides with numerical examples for shortest path finding and distance vector routing.',
    fileName: 'CN_Unit3_Routing_Algorithms.pdf',
    fileSize: '4.2 MB',
    uploadedAt: '18 Sep 2026',
  },
  {
    id: 2,
    title: 'Unit 2: Relational Algebra & Normalization 1NF to BCNF',
    subjectName: 'Database Management Systems',
    subjectCode: 'CS-602',
    professorName: 'Prof. Sneha Sharma',
    description: 'Step-by-step problem solver for finding candidate keys and decomposition to 3NF/BCNF without data loss.',
    fileName: 'DBMS_Unit2_Normalization_Guide.pdf',
    fileSize: '3.8 MB',
    uploadedAt: '15 Sep 2026',
  },
  {
    id: 3,
    title: 'Unit 1 & 2: Supervised Learning, Linear Regression & Gradient Descent',
    subjectName: 'Machine Learning & AI',
    subjectCode: 'CS-603',
    professorName: 'Dr. Rajesh Pandey',
    description: 'Mathematical foundations of cost function, learning rate optimization, and Python NumPy implementations.',
    fileName: 'ML_Unit1_2_Linear_Regression_Notes.pdf',
    fileSize: '6.5 MB',
    uploadedAt: '12 Sep 2026',
  },
  {
    id: 4,
    title: 'Unit 4: Virtual Memory, Paging & Page Replacement Algorithms',
    subjectName: 'Operating Systems',
    subjectCode: 'CS-604',
    professorName: 'Prof. Amit Patel',
    description: 'FIFO, LRU, Optimal page replacement simulations and thrashing prevention mechanisms.',
    fileName: 'OS_Unit4_Virtual_Memory_FIFO_LRU.pdf',
    fileSize: '2.9 MB',
    uploadedAt: '10 Sep 2026',
  },
  {
    id: 5,
    title: 'Docker & Kubernetes Fundamentals Handout',
    subjectName: 'Cloud Computing & DevOps',
    subjectCode: 'CS-605',
    professorName: 'Prof. Neha Gupta',
    description: 'Hands-on lab cheat sheet for building Dockerfiles, container networking, and deploying pods on K8s.',
    fileName: 'DevOps_Docker_Kubernetes_Lab_Guide.pdf',
    fileSize: '5.1 MB',
    uploadedAt: '05 Sep 2026',
  },
];

export const mockNotices: Notice[] = [
  {
    id: 1,
    title: '📢 Mandatory 75% Attendance Requirement for Mid-Sem Exam',
    message: 'All students are hereby notified that as per RGPV guidelines, a minimum of 75% attendance is compulsory to appear in the upcoming Mid-Semester examination. Students in the warning/danger zone must attend regular remedial sessions.',
    creatorName: 'Academic Section / Dean Academics',
    targetAudience: 'All B.Tech Students',
    isImportant: true,
    createdAt: '19 Sep 2026',
    category: 'exam',
  },
  {
    id: 2,
    title: '💡 Smart India Hackathon (SIH 2026) Internal College Screening',
    message: 'Interested teams from CSE, AD & IT departments are invited to submit their innovative problem solutions before 28th September. Top 5 teams will represent our college at national level.',
    creatorName: 'Prof. Sneha Sharma (Innovation Cell)',
    targetAudience: 'CSE & Allied Branches',
    isImportant: false,
    createdAt: '18 Sep 2026',
    category: 'event',
  },
  {
    id: 3,
    title: '🚌 Route 4 Bus Timings Adjusted for Evening Lab Batches',
    message: 'The evening departure for College Bus Route 4 (Indore Bypass to Campus) has been shifted from 04:30 PM to 05:00 PM to accommodate students attending 2-hour lab sessions.',
    creatorName: 'Transport Officer',
    targetAudience: 'Bus Commuters',
    isImportant: false,
    createdAt: '16 Sep 2026',
    category: 'transport',
  },
  {
    id: 4,
    title: '📚 Central Library Extended Hours & Book Bank Distribution',
    message: 'The central library will remain open till 08:00 PM during mid-semester examinations. Book bank sets for 6th semester can be collected from Counter 2.',
    creatorName: 'Head Librarian',
    targetAudience: 'All Students',
    isImportant: false,
    createdAt: '14 Sep 2026',
    category: 'academic',
  },
];

export const mockExamMarks: ExamMark[] = [
  {
    subjectCode: 'CS-601',
    subjectName: 'Computer Networks',
    marksObtained: 27,
    totalMarks: 30,
    grade: 'A+',
    examType: 'Mid-Term 1',
  },
  {
    subjectCode: 'CS-602',
    subjectName: 'Database Management Systems',
    marksObtained: 28,
    totalMarks: 30,
    grade: 'A+',
    examType: 'Mid-Term 1',
  },
  {
    subjectCode: 'CS-603',
    subjectName: 'Machine Learning & AI',
    marksObtained: 22,
    totalMarks: 30,
    grade: 'B+',
    examType: 'Mid-Term 1',
  },
  {
    subjectCode: 'CS-604',
    subjectName: 'Operating Systems',
    marksObtained: 26,
    totalMarks: 30,
    grade: 'A',
    examType: 'Mid-Term 1',
  },
];

export const mockFeeStatus: FeeStatus = {
  totalFee: 65000,
  paidFee: 65000,
  pendingFee: 0,
  dueDate: '30 Oct 2026',
  status: 'cleared',
};
