"""Increase branch column length

Revision ID: 9e9212626a9e
Revises: d7eee3d7176e
Create Date: 2026-02-25 22:03:57.328113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e9212626a9e'
down_revision = 'd7eee3d7176e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('current_semester', schema=None) as batch_op:
        batch_op.alter_column('branch',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=100),
               existing_nullable=False)

    with op.batch_alter_table('notices', schema=None) as batch_op:
        batch_op.alter_column('branch',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=100),
               existing_nullable=True)

    with op.batch_alter_table('rgpv_schemes', schema=None) as batch_op:
        batch_op.alter_column('branch',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=100),
               existing_nullable=False)

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('branch',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=100),
               existing_nullable=False)

    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.alter_column('branch',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=100),
               existing_nullable=False)

    with op.batch_alter_table('timetable_slots', schema=None) as batch_op:
        batch_op.alter_column('branch',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=100),
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('branch',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('branch',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)

    with op.batch_alter_table('timetable_slots', schema=None) as batch_op:
        batch_op.alter_column('branch',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.alter_column('branch',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('branch',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    with op.batch_alter_table('rgpv_schemes', schema=None) as batch_op:
        batch_op.alter_column('branch',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    with op.batch_alter_table('notices', schema=None) as batch_op:
        batch_op.alter_column('branch',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)

    with op.batch_alter_table('current_semester', schema=None) as batch_op:
        batch_op.alter_column('branch',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###
