"""Fresh migration aligned with existing DB

Revision ID: d7eee3d7176e
Revises: 
Create Date: 2025-11-27 12:34:58.887458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7eee3d7176e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_table('email_logs')
    with op.batch_alter_table('student_answers', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.create_unique_constraint('unique_attempt_question', ['attempt_id', 'question_id'])

    with op.batch_alter_table('tests', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_security_code', ['security_code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tests', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('student_answers', schema=None) as batch_op:
        batch_op.drop_constraint('unique_attempt_question', type_='unique')
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    op.create_table('email_logs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('recipient', sa.VARCHAR(length=120), nullable=False),
    sa.Column('subject', sa.VARCHAR(length=200), nullable=False),
    sa.Column('body', sa.TEXT(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
